// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwQdt3od2AZQnA1-zJAYXjDOtaw1NNiQ',
    appId: '1:885596504475:android:c42aa736262bef7798613e',
    messagingSenderId: '885596504475',
    projectId: 'my-test-project-d6bf3',
    storageBucket: 'my-test-project-d6bf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_pJMip86AQ1glinjYh3debKt8eSNuuv8',
    appId: '1:885596504475:ios:637f98324bdbc72a98613e',
    messagingSenderId: '885596504475',
    projectId: 'my-test-project-d6bf3',
    storageBucket: 'my-test-project-d6bf3.firebasestorage.app',
    androidClientId: '885596504475-fse21ajthbg9gdsumi7abii6smpqorl5.apps.googleusercontent.com',
    iosClientId: '885596504475-5igevm63drk9v8l6uant2p5astopfbl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pathaoHeros',
  );
}
